-- Exported from QuickDBD: https://www.quickdatabasediagrams.com/
-- Link to schema: https://app.quickdatabasediagrams.com/#/d/jBdUjq
-- NOTE! If you have used non-SQL datatypes in your design, you will have to change these here.

-- Modify this code to update the DB schema diagram.
-- To reset the sample schema, replace everything with
-- two dots ('..' - without quotes).

DROP TABLE DEPT_EMP ;
DROP TABLE DEPT_MANAGER;
DROP TABLE DEPTMTS;
DROP TABLE SALARIES;
DROP TABLE EMPLOYEES;
DROP TABLE TITLES;


CREATE TABLE DEPTMTS (
    DEPT_ID VARCHAR(5)   NOT NULL,
    DEPT_NAME VARCHAR(40)   NOT NULL,
    CONSTRAINT pk_DEPTMTS PRIMARY KEY (
        DEPT_ID
     )
);

CREATE TABLE DEPT_EMP (
    EMP_ID VARCHAR(6)   NOT NULL,
    DEPT_ID VARCHAR(5)   NOT NULL
);

CREATE TABLE DEPT_MANAGER (
    DEPT_ID VARCHAR(5)   NOT NULL,
    EMP_ID VARCHAR(6)   NOT NULL
);

CREATE TABLE EMPLOYEES (
    EMP_ID VARCHAR(6)   NOT NULL,
    EMP_TITLE_ID VARCHAR(6)   NOT NULL,
    BIRTH_DATE DATE   NOT NULL,
    FIRST_NAME VARCHAR(30)   NOT NULL,
    LAST_NAME VARCHAR(30)   NOT NULL,
    SEX VARCHAR(1)   NOT NULL,
    HIRE_DATE DATE   NOT NULL,
    CONSTRAINT pk_EMPLOYEES PRIMARY KEY (
        EMP_ID
     )
);

CREATE TABLE SALARIES (
    EMP_ID VARCHAR(6)   NOT NULL,
    SALARY DECIMAL(10,2)   NOT NULL,
    CONSTRAINT pk_SALARIES PRIMARY KEY (
        EMP_ID
     )
);

CREATE TABLE TITLES (
    TITLE_ID VARCHAR(6)   NOT NULL,
    TITLE VARCHAR(30)   NOT NULL,
    CONSTRAINT pk_TITLES PRIMARY KEY (
        TITLE_ID
     )
);

ALTER TABLE DEPT_EMP ADD CONSTRAINT fk_DEPT_EMP_EMP_ID FOREIGN KEY(EMP_ID)
REFERENCES EMPLOYEES (EMP_ID);

ALTER TABLE DEPT_EMP ADD CONSTRAINT fk_DEPT_EMP_DEPT_ID FOREIGN KEY(DEPT_ID)
REFERENCES DEPTMTS (DEPT_ID);

ALTER TABLE DEPT_MANAGER ADD CONSTRAINT fk_DEPT_MANAGER_DEPT_ID FOREIGN KEY(DEPT_ID)
REFERENCES DEPTMTS (DEPT_ID);

ALTER TABLE DEPT_MANAGER ADD CONSTRAINT fk_DEPT_MANAGER_EMP_ID FOREIGN KEY(EMP_ID)
REFERENCES EMPLOYEES (EMP_ID);

ALTER TABLE EMPLOYEES ADD CONSTRAINT fk_EMPLOYEES_EMP_TITLE_ID FOREIGN KEY(EMP_TITLE_ID)
REFERENCES TITLES (TITLE_ID);

ALTER TABLE SALARIES ADD CONSTRAINT fk_SALARIES_EMP_ID FOREIGN KEY(EMP_ID)
REFERENCES EMPLOYEES (EMP_ID);

